### ISSUE TITLE
Persistent client subscription

### ISSUE THREAD

**Issue by gualtrapa** [eclipse/paho.mqtt-sn.embedded-c#115] opened 2018-06-15 10:36 UTC
I´m trying to make persistent subscribtions on MQTT-SN Gateway. For getting that I'm using a command line  MQTT-SN client executing:

`./mqtt-sn-sub -p 5223 -t "test" -c -q 1 -i "receiver"`

From the command line client I make a publication using
 `./mqtt-sn-pub -p 5223 -t "test" -m "hello" -q 1 -i "publisher"`

If the receiver is connected when I launch the publication, the message arrives as expected. 

But if I execute the following steps:

1. Create a subscription to topic 'test' with clean session to false:
`./mqtt-sn-sub -p 5223 -t "test" -c -q 1 -i "receiver"`

2. Disconnect the receiver form the GW

3. Publish on 'test' topic
`./mqtt-sn-pub -p 5223 -t "test" -m "hello" -q 1 -i "publisher"`

4. Connect to GW with "receiver" Id

No Messages arrives to the receiver and the GW logs show "Invalid Topic. PUBLISH message is canceled.". The complete logs shows:
```
20180615 122837.132   CONNECT           <---  receiver                            04 00 01 00 0A 72 65 63 65 69 76 65 72
20180615 122837.133   CONNECT           ===>  receiver                            10 14 00 04 4D 51 54 54 04 00 00 0A 00 08 72 65 63 65 69 76 65 72
20180615 122837.173   CONNACK           <===  receiver                            20 02 01 00
20180615 122837.173   CONNACK           --->  receiver                            05 00

20180615 122837.173   SUBSCRIBE   0001  <---  receiver                            12 20 00 01 74 65 73 74
20180615 122837.174   SUBSCRIBE   0001  ===>  receiver                            82 09 00 01 00 04 74 65 73 74 01
20180615 122837.174   SUBACK      0001  <===  receiver                            90 03 00 01 01
20180615 122837.174   SUBACK      0001  --->  receiver                            13 20 00 01 00 01 00
20180615 122840.567   DISCONNECT        <---  receiver                            18
20180615 122840.567   DISCONNECT        --->  receiver                            18
20180615 122840.567   DISCONNECT        ===>  receiver                            E0 00
20180615 122842.000   ADVERTISE         --->  Clients                             00 02 03 84

20180615 122847.084   CONNECT           <---  publisher                           04 04 01 00 0A 70 75 62 6C 69 73 68 65 72
20180615 122847.085   CONNECT           ===>  publisher                           10 15 00 04 4D 51 54 54 04 02 00 0A 00 09 70 75 62 6C 69 73 68 65 72
20180615 122847.104   CONNACK           <===  publisher                           20 02 00 00
20180615 122847.104   CONNACK           --->  publisher                           05 00

20180615 122847.104   REGISTER    0001  <---  publisher                           0A 00 00 00 01 74 65 73 74
20180615 122847.104   REGACK      0001  --->  publisher                           0B 00 01 00 01 00

20180615 122847.105   PUBLISH     0002  <---  publisher                           0C 20 00 01 00 02 68 65 6C 6C 6F
20180615 122847.105   PUBLISH     0002  ===>  publisher                           32 0D 00 04 74 65 73 74 00 02 68 65 6C 6C 6F
20180615 122847.105   PUBACK      0002  <===  publisher                           40 02 00 02
20180615 122847.105   PUBACK      0002  --->  publisher                           0D 00 01 00 02 00
20180615 122847.106   DISCONNECT        <---  publisher                           18
20180615 122847.106   DISCONNECT        --->  publisher                           18
20180615 122847.106   DISCONNECT        ===> !                                  E0 00

20180615 122851.724   CONNECT           <---  receiver                            04 00 01 00 0A 72 65 63 65 69 76 65 72
20180615 122851.724   CONNECT           ===>  receiver                            10 14 00 04 4D 51 54 54 04 00 00 0A 00 08 72 65 63 65 69 76 65 72
20180615 122852.108   CONNACK           <===  receiver                            20 02 01 00
20180615 122852.108   CONNACK           --->  receiver                            05 00

20180615 122852.108   PUBLISH     0007  <===  receiver                            32 0D 00 04 74 65 73 74 00 07 68 65 6C 6C 6F
 Invalid Topic. PUBLISH message is canceled.
20180615 122852.108   PUBACK      0007  ===>  receiver                            40 02 00 07

20180615 122852.108   SUBSCRIBE   0001  <---  receiver                            12 20 00 01 74 65 73 74
20180615 122852.109   SUBSCRIBE   0001  ===>  receiver                            82 09 00 01 00 04 74 65 73 74 01
20180615 122852.154   SUBACK      0001  <===  receiver                            90 03 00 01 01
20180615 122852.154   SUBACK      0001  --->  receiver                            13 20 00 01 00 01 00
```
Are presistent subscriptions availables with the current GW implementation?

Maybe I´m doing something wrong or missing something. Any help is wellcome.

Thanks in advance

**Comment by ty4tw** [comment] 2018-06-15 23:27
Hi gualtrapa,

Thank you for your cooperation.  
I think there is a bug in GW.　(GatewayTester program didn't test it.)
I will check it out ASAP.  but it takes a while.

**Comment by gualtrapa** [comment] 2018-06-16 07:37
Many thanks! 

If I can be of any assistance please ley me know

**Comment by ty4tw** [comment] 2018-06-28 23:06
I could reproduce the same bug. 
The lifetime of the subscribed topic was not persistent only while the gateway was running.
Even if topic is persistent, when the subscribe client reconnect, it should sent REGISTER message to get a topic ID. Otherwise, the client can not identify the topic when it receives a PUBLISH message.   
I think that non-clean sessions of MQTT-SN are meaningful for short topics.
Therefore, I'd like this issue as a future enhancement.

**Comment by gualtrapa** [comment] 2018-06-29 07:44
Hi,

Thanks for your update. 

Re-reading MQTT-SN Protocol Specification, I find up “pre-defined” topic ids. Basically, a “pre-defined” topic id, is a topic id whose mapping to a topic name is known in advance by both the client’s application and the gateway. This feature can be very usefull in our use case.

Does the GW support (or plan to support)  “pre-defined” topic id? 

Thanks in advance

**Comment by ty4tw** [comment] 2018-06-29 08:37
GW doesn't support it. because, Broker doesn't support it.
you should use short topic instead of pre-defined ID.

**Comment by ty4tw** [comment] 2018-07-01 08:32
How do you SUBSCRIBE the pre-defined Topic?
if the client can subscribe the topic, it is no need to use the pre-defined topics.
my understanding is that Pre-defined Topic is for PUBLISH.

**Comment by ty4tw** [comment] 2018-07-04 00:13
Thank you for your information.
I'm working on it as a Issue #117.
can we close this issue?

**Closed** 2018-07-06 21:48 UTC

**Comment by gualtrapa** [comment] 2018-07-07 05:53
Sorry for the late response. Maybe you can include that persistente subscriptions working with long topics are not supported on REEDME.

Thanks
